name: "Add Member Card"
description: "Request to add yourself (or someone else, with permission) to the Members page"
title: "[Member] Add: <Full Name>"
labels: ["members", "content", "good first issue"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to the EAAMO UDS Working Group website! Fill out the fields below to be added to the Members section.

        We support either:
        - Local optimized image checked into the repo (recommended): `src/assets/members/<your-photo>.jpg`
        - Remote image URL (e.g., GitHub avatar): e.g., `https://avatars.githubusercontent.com/u/59738610?v=4`

        A maintainer will create a file at `src/content/members/<your-slug>.md` using this info.

  - type: input
    id: name
    attributes:
      label: Full name
      placeholder: "Jane Doe"
    validations:
      required: true

  - type: input
    id: role
    attributes:
      label: Role / Position (optional)
      placeholder: "PhD Student"
    validations:
      required: false

  - type: input
    id: affiliation
    attributes:
      label: Affiliation (optional)
      placeholder: "Cornell University"
    validations:
      required: false

  - type: dropdown
    id: image_type
    attributes:
      label: Image type
      options:
        - Remote URL (link)
        - Local file path (in repo)
    validations:
      required: true

  - type: input
    id: image
    attributes:
      label: Image URL or repo path
      placeholder: "https://avatars.githubusercontent.com/u/59738610?v=4" 
      description: |
        If using a local file, place it under `src/assets/members/` and provide the relative path, e.g., `../../assets/members/jane-doe.jpg`.
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Personal website or profile (optional)
      placeholder: "https://example.com"
    validations:
      required: false

  - type: input
    id: order
    attributes:
      label: Ordering (optional)
      placeholder: "e.g. 1 (lower shows first)"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notes for maintainers (optional)
      placeholder: "Any special requests or context?"
    validations:
      required: false

  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      description: "Please confirm the following"
      options:
        - label: "I consent to having my name, role, affiliation, and image listed on the EAAMO UDS site."
          required: true

  - type: markdown
    attributes:
      value: |
        Example member file the maintainers will create:

        ```yaml
        ---
        name: "Jane Doe"
        role: "PhD Student"
        affiliation: "Cornell University"
        # Either a local asset...
        # image: "../../assets/members/jane-doe.jpg"
        # ...or a remote URL
        # image: "https://avatars.githubusercontent.com/u/59738610?v=4"
        website: "https://example.com"
        order: 10
        tags: ["member"]
        ---
        ```


