name: Add Member from PR Template

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  add-member:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Extract member info from PR body
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request?.body || '';
            const match = body.match(/<!-- MEMBER-INFO-START -->[\s\S]*?```yaml([\s\S]*?)```[\s\S]*?<!-- MEMBER-INFO-END -->/);
            if (!match) {
              core.setFailed('PR is missing MEMBER-INFO YAML block');
              return;
            }
            // Minimal YAML parser for simple key: value pairs used here
            const lines = match[1].split(/\r?\n/);
            const data = {};
            for (const line of lines) {
              const m = line.match(/^\s*([A-Za-z0-9_]+)\s*:\s*"?(.*?)"?\s*$/);
              if (m) data[m[1]] = m[2];
            }
            const invalids = new Set(['', '_no response_', 'n/a', 'na', 'none', 'null', 'remote url (link)']);
            const sanitizeWebsite = (u) => {
              const s = (u || '').trim();
              if (invalids.has(s.toLowerCase())) return 'https://example.com';
              try { new URL(s); return s; } catch { return 'https://example.com'; }
            };
            const sanitizeImage = (img) => {
              const s = (img || '').trim();
              if (invalids.has(s.toLowerCase())) return '../../assets/vista.jpg';
              if (/^https?:/i.test(s)) return s;
              if (/^(\.\.\/){1,2}?assets\//i.test(s) || /^src\//i.test(s)) return s;
              return '../../assets/vista.jpg';
            };
            const sanitizeOrder = (_) => 999;
            const slugify = s => s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
            const slug = slugify(data.name || 'member');
            const name = (data.name || '').trim();
            const role = (data.role || '').trim();
            const affiliation = (data.affiliation || '').trim();
            const image = sanitizeImage(data.image);
            const website = sanitizeWebsite(data.website);
            const order = String(sanitizeOrder(data.order));

            core.setOutput('found', 'true');
            core.setOutput('name', name);
            core.setOutput('role', role);
            core.setOutput('affiliation', affiliation);
            core.setOutput('image', image);
            core.setOutput('website', website);
            core.setOutput('order', order);
            core.setOutput('slug', slug);
            if (!name) {
              core.setFailed('Missing required field: name');
              return;
            }

      - name: Ensure members assets directory
        if: steps.extract.outputs.found == 'true'
        run: mkdir -p src/assets/members

      - name: Download remote image if URL
        if: steps.extract.outputs.found == 'true' && startsWith(steps.extract.outputs.image, 'http')
        run: |
          url="${{ steps.extract.outputs.image }}"
          # Extract extension from URL, strip querystring; default to jpg
          ext=$(echo "$url" | sed -E 's/.*\.([A-Za-z0-9]+)(\?.*)?$/\1/')
          if [ -z "$ext" ]; then ext=jpg; fi
          out="src/assets/members/${{ steps.extract.outputs.slug }}.$ext"
          curl -L "$url" -o "$out"
          echo "local_image_path=$out" >> $GITHUB_OUTPUT

      - name: Resolve image path
        id: img
        if: steps.extract.outputs.found == 'true'
        run: |
          IMAGE_INPUT="${{ steps.extract.outputs.image }}"
          if echo "$IMAGE_INPUT" | grep -qi '^http'; then
            # Use the downloaded file path converted to content relative path
            DOWNLOADED="${{ steps.extract.outputs.slug }}"
            # Find the file matching the slug in assets/members
            FILE=$(ls src/assets/members/${DOWNLOADED}.* | head -n1)
            REL="../../assets/members/$(basename "$FILE")"
            echo "path=$REL" >> $GITHUB_OUTPUT
          else
            echo "path=$IMAGE_INPUT" >> $GITHUB_OUTPUT
          fi

      - name: Create member content file
        if: steps.extract.outputs.found == 'true'
        run: |
          mkdir -p src/content/members
          cat > src/content/members/${{ steps.extract.outputs.slug }}.md <<'EOF'
          ---
          name: "${{ steps.extract.outputs.name }}"
          role: "${{ steps.extract.outputs.role }}"
          affiliation: "${{ steps.extract.outputs.affiliation }}"
          image: "${{ steps.img.outputs.path }}"
          website: "${{ steps.extract.outputs.website }}"
          order: ${{ steps.extract.outputs.order }}
          tags: ["member"]
          ---
          EOF

      - name: Commit changes
        if: steps.extract.outputs.found == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/content/members src/assets/members || true
          git commit -m "chore(members): add ${{ steps.extract.outputs.slug }} via PR template" || echo "No changes to commit"

      - name: Push changes
        if: steps.extract.outputs.found == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}

      - name: Enable auto-merge
        if: steps.extract.outputs.found == 'true'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash


